"""Contract tests for the governed Cline product launcher generated by
tools/lbe_product_integration.ps1 (Write-ClineLauncher + install steps)."""
from __future__ import annotations

from pathlib import Path


SCRIPT = Path(__file__).resolve().parents[1] / "tools" / "lbe_product_integration.ps1"


def _cline_launcher_source() -> str:
    source = SCRIPT.read_text(encoding="utf-8")
    marker = "$launcher = @'"
    start = source.rfind(marker)
    assert start != -1, "Write-ClineLauncher lbe-cline.ps1 here-string missing"
    end = source.find("'@", start + len(marker))
    assert end != -1, "unterminated lbe-cline.ps1 here-string"
    return source[start + len(marker):end]


def test_write_cline_launcher_exists_and_is_wired_into_the_package() -> None:
    source = SCRIPT.read_text(encoding="utf-8")
    assert "function Write-ClineLauncher" in source
    assert 'Write-ClineLauncher -PackageRoot $packageRoot' in source


def test_governed_addon_is_the_registered_mcp_server_with_no_auto_approval() -> None:
    launcher = _cline_launcher_source()
    assert 'args = @("-m", "lbe_guard_inspector.runtime.cline_governed_birdeye", "--stdio")' in launcher
    assert "autoApprove = @()" in launcher
    assert 'mcpServers."lbe-birdeye"' in launcher


def test_provisioning_is_workspace_scoped_and_never_touches_global_settings() -> None:
    launcher = _cline_launcher_source()
    assert 'Join-Path $clineDir "rules"' in launcher
    assert 'Join-Path $clineDir "mcp.json"' in launcher
    # Project .cline only: no reference to npm shims or global CLI settings.
    assert "AppData\\Roaming\\npm" not in launcher
    assert "alwaysApply" not in launcher


def test_launcher_resolves_global_cline_or_fails_explicitly() -> None:
    launcher = _cline_launcher_source()
    assert 'Join-Path $env:APPDATA "npm\\cline.cmd"' in launcher
    assert '"cline.cmd"' in launcher
    assert "$cline = $candidate; break" in launcher
    assert 'throw "Cline CLI not found. Install @cline/cli so it resolves, then retry."' in launcher


def test_launcher_spawns_textual_ui_in_the_governed_workspace() -> None:
    launcher = _cline_launcher_source()
    assert '$cliArgs = @("--tui", "-c", $workspaceFull)' in launcher
    assert "& $cline @cliArgs" in launcher
    assert "exit $LASTEXITCODE" in launcher


def test_launcher_requires_a_governed_session_and_binds_env() -> None:
    launcher = _cline_launcher_source()
    assert "LBE governed session id is required" in launcher
    assert 'if (-not $SessionId) { $SessionId = $env:LBE_SESSION_ID }' in launcher
    assert "$env:LBE_WALL_DATABASE = [IO.Path]::GetFullPath($Database)" in launcher
    assert "$env:LBE_TARGET_WORKSPACE = $workspaceFull" in launcher


def test_launcher_reuses_installed_birdeye_identity_from_config_like_lbe_launch() -> None:
    launcher = _cline_launcher_source()
    assert '$env:LBE_BIRDEYE_MCP_PYTHON = [string]$mcp.python' in launcher
    assert '$env:LBE_BIRDEYE_MCP_SERVER = [string]$mcp.server' in launcher


def test_installer_ships_lbe_cline_launcher_and_bin_entrypoint() -> None:
    source = SCRIPT.read_text(encoding="utf-8")
    assert 'Join-Path $PSScriptRoot "lbe-cline.ps1"' in source
    assert 'Copy-Item -LiteralPath $clineLauncher -Destination (Join-Path $InstallRoot "lbe-cline.ps1") -Force' in source
    assert '$clineBinCmd = Join-Path $binDir "lbe-cline.cmd"' in source
    assert 'powershell -NoProfile -ExecutionPolicy Bypass -File "%LBE_INSTALL_ROOT%\\lbe-cline.ps1" %*' in source